# latexmkrc for MSc_layout.tex
# Build chain: lualatex -> biber -> lualatex -> lualatex
# Usage: latexmk -r latexmkrc MSc_layout.tex
# (LaTeX Workshop in VS Code can also call latexmk directly; see .vscode/settings.json)

$pdf_mode = 4;          # 4 = use lualatex to produce pdf directly
$lualatex = 'lualatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';
$biber    = 'biber %O %B';
$bibtex_use = 2;        # run biber/bibtex whenever bcf/aux changed, even mid-run
$pdflatex = $lualatex;  # in case any tool calls $pdflatex by habit

# Clean up nomenclature / glossary / index / biblatex byproducts too
$clean_ext = 'bbl bcf run.xml nlo nls glo gls glg ist idx ind ilg synctex.gz';

# Make sure latexmk reruns enough times to settle TOC/nomenclature/bib/acronyms
$max_repeat = 5;
